### ISSUE TITLE
The error I encountered while preparing my scenes using code extract_scannet_scene

### ISSUE THREAD

**Issue by myself-oriented** [barbararoessle/dense_depth_priors_nerf#11]
Hi, thanks for your code!
I prepare my scenes using the code "**extract_scannet_scene**",which has two input parameters, one is "**path to scene**" and the other is "**path to ScanNet**". For parameter "**path to ScanNet**", I type the path of trained network downloaded in _step1_(named _20211027_092436.tar_), but an error occurs when running the code, prompting "**_! _src_empty() in 'cvtcolor_**' ".I open "**extract_scannet_scene.cpp**" and find "**boost:: Filesystem ::path path2scannet(argv[2])**" and "**boost::filesystem::path path2scannetscene(path2scannet/"scans_test"/config.kname);** " in lines 161 and 163 of the "**main()**".I find that the trained ScanNet(_20211027_092436.tar_) does not contain the folder "**scans_test**", so I would like to know how to deal with this problem, whether I need to train a ScanNet by myself when preparing my own scenes, or there is something wrong with my method .Looking forward to your reply!

**Comment by barbararoessle** [comment]
Hi, `Path to ScanNet` is the path to the directory into which you extracted the ScanNet dataset, as described [here](https://github.com/barbararoessle/dense_depth_priors_nerf/blame/master/README.md#L12).

**Comment by nanxiangriluo** [comment]
Hi,thanks for you code!
I prepare  the config.josn for my sence .I wonder how "max_depth" and "dist2m" are obtained.Looking forward to your reply!

**Comment by barbararoessle** [comment]
Hi, [this](https://github.com/barbararoessle/dense_depth_priors_nerf/issues/3) should answer your question.
