### ISSUE TITLE
About depth completion?

### ISSUE THREAD

**Issue by MELANCHOLY828** [barbararoessle/dense_depth_priors_nerf#12]
This article uses depth completion instead of other depth-predicting networks (such as MVS), is there any difference? Is our deep completion network better?

**Comment by barbararoessle** [comment]
A monocular depth predictor will produce dense depth maps that are not consistent in scale across the input views. When we have sparse depth that is consistent in scale across the input views (like a sparse reconstruction from structure from motion), using depth completion has the advantage that the resulting dense depth maps will also be mostly consistent in scale.
