### ISSUE TITLE
fail to build extract_scannet_scene.cpp

### ISSUE THREAD

**Issue by EchoTHChen** [barbararoessle/dense_depth_priors_nerf#2]
after I run the command `make install` for building preprocessing, I met the error:

`preprocessing/io_colmap/src/colmap_reader.cpp:84:117: error: no matching function for call to ‘rotate(glm::mat4, float, glm::vec3)’
   const glm::mat4 rot_cam2cam = glm::rotate(glm::mat4(1.0f), glm::radians(180.0f), glm::vec3(1.0f, 0.0f, 0.0f));
                                                                                                               ^
In file included from /usr/include/glm/gtc/quaternion.hpp:434:0,
                 from dense_depth_priors_nerf-master/preprocessing/io_colmap/src/colmap_reader.cpp:6:
/usr/include/glm/gtc/quaternion.inl:560:33: note: candidate: template<class T, glm::qualifier Q> glm::tquat<T, Q> glm::rotate(const glm::tquat<T, Q>&, const T&, const glm::vec<3, T, Q>&)
  GLM_FUNC_QUALIFIER tquat<T, Q> rotate(tquat<T, Q> const& q, T const& angle, vec<3, T, Q> const& v)
                                 ^~~~~~
`

 I install glm by sudo apt install libglm-dev. Finally glm-0.9.9~a2-2 is installed. But it seems that it is not suitable for this program.  Could you tell me how you install the glm or how you build the environment of preprocessing?

**Comment by sMamooler** [comment]
Hello,

Could you please explain how you resolved this issue?
I'm facing the same error.

Thanks!

**Comment by EchoTHChen** [comment]
> 

I build GLM library from source code instead of `apt install libglm-dev`.
