### ISSUE TITLE
Can you tell me which version about the pytorch used to train the depth completion model ? Thank you!

### ISSUE THREAD

**Issue by Flockmaster1597** [barbararoessle/dense_depth_priors_nerf#4]

**Comment by barbararoessle** [comment]
It was trained with pytorch version 1.9.0+cu111

**Comment by Flockmaster1597** [comment]
Thanks for your reply, I've been able to complete the output rendering video using the model and data you provided. But the effect is relatively poor, only the desk, window and piano area can be seen clearly, which may be due to the problem of parameters?

**Comment by Flockmaster1597** [comment]
![选区_004](https://user-images.githubusercontent.com/25261129/165888360-f614d045-0989-4ee5-a873-f58c16197353.png)

**Comment by Flockmaster1597** [comment]
![选区_006](https://user-images.githubusercontent.com/25261129/165888596-10f494b6-5f94-434f-8a9a-1b0ae5b1a72f.png)

**Comment by barbararoessle** [comment]
yeah, that does not look right. 

To check, I went through the steps from scratch, in case it helps, here are the details:

**Setup:**
I downloaded the scene and the depth completion network weights from the google drive and recreated my python environment:
```
python3 -m venv .venv
.venv/bin/python3 -m pip install -r requirements.txt
```
which gave me the following versions:
```
Successfully installed PyWavelets-1.3.0 absl-py-1.0.0 cachetools-5.0.0 certifi-2021.10.8 charset-normalizer-2.0.12 configargparse-1.5.3 google-auth-2.6.6 google-auth-oauthlib-0.4.6 grpcio-1.44.0 idna-3.3 imageio-2.18.0 importlib-metadata-4.11.3 lpips-0.1.4 markdown-3.3.6 networkx-2.8 numpy-1.22.3 oauthlib-3.2.0 opencv-python-4.5.5.64 packaging-21.3 pandas-1.4.2 pillow-9.1.0 protobuf-3.20.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-3.0.8 python-dateutil-2.8.2 pytz-2022.1 requests-2.27.1 requests-oauthlib-1.3.1 rsa-4.8 scikit-image-0.19.2 scipy-1.8.0 six-1.16.0 tensorboard-2.8.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tifffile-2022.4.28 torch-1.11.0 torchvision-0.12.0 tqdm-4.64.0 typing-extensions-4.2.0 urllib3-1.26.9 werkzeug-2.1.2 wheel-0.37.1 zipp-3.8.0
```
**Optimize NeRF with depth priors:**
```
.venv/bin/python3 run_nerf.py train --scene_id scene0710_00 --data_dir /cluster/gimli/brossle/gdrive_scenes --depth_prior_network_path /cluster/erebor/brossle/pretrained_models/20211027_092436.tar --ckpt_dir /cluster/erebor/brossle/nerf_models
```
Before the script starts the optimization, it prints the RMSE of the completed depth maps compared to the ScanNet sensor depth in meters. For `scene0710_00` it should be:
```
Depth maps have RMSE 0.1758 after completion
```
If you obtain a significantly different RMSE, then something is wrong with the depth completion. 

After NeRF optimization, the test metrics should be similar to:
```
psnr: 20.486580967903137
ssim: 0.7095631882548332
lpips: 0.3357847332954407
depth_rmse: 0.18051430769264698
```

**Render a video:**
```
.venv/bin/python3 run_nerf.py video --expname 20220429_094145_scene0710_00 --data_dir /cluster/gimli/brossle/gdrive_scenes --ckpt_dir /cluster/erebor/brossle/nerf_models
```

The video looks like this:

https://user-images.githubusercontent.com/78485261/166218555-c96051fe-df3d-4c8d-8a1c-3534cbfa538e.mp4

**Comment by Flockmaster1597** [comment]
With your help I got the correct result, thanks a lot! 
The reason may be that I used an inappropriate version of pytorch first and modified the parameters of several pytorch functions, resulting in problems with the acquired depth map。
I got right result using pytorch version 1.11.0+cu113.[选区_031](https://user-images.githubusercontent.com/25261129/167237301-9312a743-f84b-4693-a91d-1c7cd56a8317.png)
！

**Comment by Flockmaster1597** [comment]
![031](https://user-images.githubusercontent.com/25261129/167239448-48c18144-70c7-415d-9172-76633de60198.png)
