### ISSUE TITLE
Could you provide the pretrained depth net on Matterport3D?

### ISSUE THREAD

**Issue by cwchenwang** [barbararoessle/dense_depth_priors_nerf#7]

**Comment by barbararoessle** [comment]
Unfortunately no. For depth prior training I recommend to consider the scenario that you plan to use the depth priors in (e.g. sparse depth density and accuracy). Details can be found [here](https://github.com/barbararoessle/dense_depth_priors_nerf/issues/1#issuecomment-1111434503)

**Comment by cwchenwang** [comment]
@barbararoessle You should provide pretrain models and the train / test split on matterport3d for future works to compare.
