### ISSUE TITLE
Hi,I can’t figure out how to load "the depth completion model trained on ScanNet",or more specific,the "data.pkl"

### ISSUE THREAD

**Issue by heihuagg** [barbararoessle/dense_depth_priors_nerf#9]
I use torch.load("the path of pretrained model")
but it says ”_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.“

my pytorch'version is 1.8.1
I want to konw your pytorch'version on save "data.pkl",

Sorry to trouble you，this bug has bothered me for a long time.
I hope you can solve my confusion.
Thanks！！！

**Comment by barbararoessle** [comment]
Hi, it was trained with pytorch version 1.9.0+cu111
Maybe the information [here](https://github.com/barbararoessle/dense_depth_priors_nerf/issues/4) helps.

**Comment by Karbo123** [comment]
@barbararoessle 
I had the same problem here. I have tried pytorch version like `1.8.0+cu111`, `1.9.0+cu111`, `1.10.2+cu111`, `1.12.1+cu116`, but unfortunately none of these worked. It is very likely that the checkpoint has been corrupted. By the way, I cannot extract the `20211027_092436.tar` on Linux platform, but I can extract on Win11, I am not sure what is wrong with the pretrained model downloaded [here](https://drive.google.com/drive/folders/1HTyigHPJKZKBWzGFoY8J2bcS-h8_SfX9).

```
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

I load the checkpoint with something like: `torch.load("./experiments_denseDepthPriors/20211027_092436/archive/data.pkl")`.

I have no idea on the way to solve it, I would truly appreciate if some hints are given.
